# basic options
title: Test
author: dezzy001
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
